[package]
org = "wso2healthcare"
name = "CcdaToFhirService"
version = "0.9.0"
distribution = "2201.7.0"
authors = ["Ballerina"]
keywords = ["Healthcare", "CCDA to FHIR", "FHIR", "CCDA"]
template = true

[build-options]
observabilityIncluded = true
