[package]
org = "wso2"
name = "Hl7v2ToFhirR4Service"
version = "1.1.0"
distribution = "2201.8.5"
authors = ["Ballerina"]
keywords = ["Healthcare","FHIR","HL7V2", "Transform"]

[build-options]
observabilityIncluded = true

## These dependencies are added due to a build issue, once Choreo supports Bal 9 these dependencies can be removed.
[[dependency]]
org = "ballerinax"
name = "health.hl7v2"
version = "2.1.0"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4"
version = "4.2.0"

[[dependency]]
org = "ballerinax"
name = "health.hl7v2commons"
version = "1.1.0"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.international401"
version = "1.2.0"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.parser"
version = "4.1.1"

[[dependency]]
org = "ballerinax"
name = "health.hl7v2.utils.v2tofhirr4"
version = "2.2.3"