[package]
org = "ballerinax"
name = "health.core.dataservice"
version = "0.1.0"
distribution = "2201.8.5"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.26"